# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme
locale: en-US
title: "Angelos Tsiaras"
description: "PhD in Astronomy"
#sub_description: '<a href="mailto:atsiaras@star.ucl.ac.uk">e-mail me</a> &nbsp; &nbsp; <a href="http://zuserver2.star.ucl.ac.uk/~atsiaras/angelos_tsiaras_cv.pdf" target="_blank">read my CV</a>'
sub_description:   '<a href="mailto:atsiaras@star.ucl.ac.uk">
                        <img src="https://atsiaras.github.io/images/email-icon.png" 
                            width="60" height="60" title="E-mail"></a> 
                    &nbsp; &nbsp;
                    <a href="http://zuserver2.star.ucl.ac.uk/~atsiaras/angelos_tsiaras_cv.pdf" target="_blank">
                        <img src="https://atsiaras.github.io/images/cv-icon.png" 
                            width="60" height="60" title="CV"></a>
                    &nbsp; &nbsp;
                    <a href="https://github.com/atsiaras" target="_blank">
                        <img src="https://atsiaras.github.io/images/github-logo.svg" 
                            width="60" height="60" title="GitHub"></a>
                    &nbsp; &nbsp;
                    <a href="https://ui.adsabs.harvard.edu/?#search/p_=0&q=Tsiaras%2C%20Angelos&sort=citation_count%20desc%2C%20bibcode%20desc" target="_blank">
                        <img src="https://atsiaras.github.io/images/adslogo.jpg" 
                            width="60" height="60" title="ADS"></a>'


baseurl: 'https://atsiaras.github.io'
url: '/'
logo: 'https://atsiaras.github.io/images/me.jpg'
urlimg: 'https://atsiaras.github.io/images/'
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Site Author
author:
  name: Angelos Tsiaras
  picture: /images/me.png
  email: atsiaras@star.ucl.ac.uk
  links:
    - title: GitHub
      url: https://github.com/atsiaras
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: GitHub
    url: https://github.com/atsiaras
    icon: fab fa-github-square
